[package]
name = "lpm_backend"
version = "0.1.0"
edition = "2024"

[dependencies]
procfs = "0.16" #The procfs crate is specifically designed to parse the Linux /proc filesystem efficiently.
nix = "0.26"    # Used for process control (kill, set priority)